/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_AMBIENTLIGHTING
  #define INTERNAL_INCLUDED_OPTION_AMBIENTLIGHTING

  #define AMBIENT_OCCLUSION
  //#define AMBIENT_DIFFUSE

#endif /* INTERNAL_INCLUDED_OPTION_AMBIENTLIGHTING */
