/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_BLOOM
  #define INTERNAL_INCLUDED_OPTION_BLOOM

  #define BLOOM

#endif /* INTERNAL_INCLUDED_OPTION_BLOOM */
