/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_DEBUGGING
  #define INTERNAL_INCLUDED_OPTION_DEBUGGING

  #define DEBUG_MODE

  //#define VISUALISE_PCSS_EDGE_PREDICTION

#endif /* INTERNAL_INCLUDED_OPTION_DEBUGGING */