/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_MATERIAL
  #define INTERNAL_INCLUDED_OPTION_MATERIAL

  #define RESOURCE_FORMAT 2 // [0 1 2 3 4]

  #define MATERIAL_DEFAULT vec4(0.0, 0.0, 0.0, 0.0)

#endif /* INTERNAL_INCLUDED_OPTION_MATERIAL */
