/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_NORMALS
  #define INTERNAL_INCLUDED_OPTION_NORMALS

  // OPAQUE
  #define NORMAL_ANGLE_OPAQUE 0.5
  #define NORMAL_ANGLE_WET 0.0
  
  // TRANSPARENT
  #define NORMAL_ANGLE_TRANSPARENT 0.03

#endif /* INTERNAL_INCLUDED_OPTION_NORMALS */
