/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_PARALLAX
  #define INTERNAL_INCLUDED_OPTION_PARALLAX

  // OPAQUE
  #define PARALLAX_OPAQUE

  #define PARALLAX_OPAQUE_DEPTH 4.0

  //#define PARALLAX_OPAQUE_QUALITY_SCALING
  #define PARALLAX_OPAQUE_QUALITY_FIXED 32

  // TRANSPARENT

#endif /* INTERNAL_INCLUDED_OPTION_PARALLAX */
