/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_POST
  #define INTERNAL_INCLUDED_OPTION_POST

  #define EXPOSURE 3.0
  #define GAMMA 2.2
  #define SATURATION 1.0

#endif /* INTERNAL_INCLUDED_OPTION_POST */
