/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_SHADOWS
  #define INTERNAL_INCLUDED_OPTION_SHADOWS

  #define SHADOW_DISTORTION_FACTOR 0.9

  #define SHADOW_FILTER_QUALITY 2 // [1 2 3 4 5 6]

#endif /* INTERNAL_INCLUDED_OPTION_SHADOWS */
