/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_VOLUMETRICS
  #define INTERNAL_INCLUDED_OPTION_VOLUMETRICS

  #define VOLUMETRICS

#endif /* INTERNAL_INCLUDED_OPTION_VOLUMETRICS */
