/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_OPTION_WAVINGTERRAIN
  #define INTERNAL_INCLUDED_OPTION_WAVINGTERRAIN

  #define WAVING_GRASS
  #define WAVING_FLOWERS
  #define WAVING_CROPS
  #define WAVING_LEAVES
  #define WAVING_VINES

#endif /* INTERNAL_INCLUDED_OPTION_WAVINGTERRAIN */
