/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SETTING_BLOOM
  #define INTERNAL_INCLUDED_SETTING_BLOOM

  #define BLOOM

#endif /* INTERNAL_INCLUDED_SETTING_BLOOM */
