/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SETTING_NORMALS
  #define INTERNAL_INCLUDED_SETTING_NORMALS

  #define _waterHeight water0 // [water0]

#endif /* INTERNAL_INCLUDED_SETTING_NORMALS */
