/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SETTING_NORMALS
  #define INTERNAL_INCLUDED_SETTING_NORMALS

  // WATER
  #define WATER_NORMAL_ANISOTROPY 0.2

  #define _waterHeight water0 // [water0 water1]

#endif /* INTERNAL_INCLUDED_SETTING_NORMALS */
