/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SETTING_PARALLAX
  #define INTERNAL_INCLUDED_SETTING_PARALLAX

  // TERRAIN
  #define PARALLAX_TERRAIN

  #define PARALLAX_TERRAIN_DEPTH 2.0 // [1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0]
  #define PARALLAX_TERRAIN_SAMPLES 64

#endif /* INTERNAL_INCLUDED_SETTING_PARALLAX */
