/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SETTING_PARALLAX
  #define INTERNAL_INCLUDED_SETTING_PARALLAX

  // TERRAIN
  #define PARALLAX_TERRAIN

  #define PARALLAX_TERRAIN_DEPTH 0.5
  #define PARALLAX_TERRAIN_QUALITY 32 // [32 48 64 80 96 112 128]

#endif /* INTERNAL_INCLUDED_SETTING_PARALLAX */
