/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SETTING_REFRACTION
  #define INTERNAL_INCLUDED_SETTING_REFRACTION

  #define REFRACTION

#endif /* INTERNAL_INCLUDED_SETTING_REFRACTION */
