/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SETTING_SKY
  #define INTERNAL_INCLUDED_SETTING_SKY

  #define SUN_SIZE 1.0
  #define MOON_SIZE 1.0

#endif /* INTERNAL_INCLUDED_SETTING_SKY */
