/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SETTING_VOLUMETRICS
  #define INTERNAL_INCLUDED_SETTING_VOLUMETRICS

  // GENERAL
  #define VOLUMETRICS

  // ATMOSPHERIC SCATTERING
  #define ATMOSPHERIC_SCATTERING

  // FOG
  #define VOLUMETRIC_FOG

  // WATER
  #define VOLUMETRIC_WATER

#endif /* INTERNAL_INCLUDED_SETTING_VOLUMETRICS */
