/*
  JCM2606.
  HALCYON.
  PLEASE READ "LICENSE.MD" BEFORE EDITING.
*/

#ifndef INTERNAL_INCLUDED_SYNTAX_SHADERS
  #define INTERNAL_INCLUDED_SYNTAX_SHADERS

  // SHADER
  #define FSH 0
  #define VSH 1

  // PROGRAM
  #define NONE 0

  #define SHADOW 1
  #define SHADOW_SOLID 2
  #define SHADOW_CUTOUT 3

  #define GBUFFERS_BASIC 4
  #define GBUFFERS_TEXTURED 5
  #define GBUFFERS_TEXTURED_LIT 6
  #define GBUFFERS_SKYBASIC 7
  #define GBUFFERS_SKYTEXTURED 8
  #define GBUFFERS_CLOUDS 9
  #define GBUFFERS_TERRAIN 10
  #define GBUFFERS_TERRAIN_SOLID 11
  #define GBUFFERS_TERRAIN_CUTOUT_MIP 12
  #define GBUFFERS_TERRAIN_CUTOUT 13
  #define GBUFFERS_DAMAGEDBLOCK 14
  #define GBUFFERS_BLOCK 15
  #define GBUFFERS_BEACONBEAM 16
  #define GBUFFERS_ITEM 17
  #define GBUFFERS_ENTITIES 18
  #define GBUFFERS_ARMOR_GLINT 19
  #define GBUFFERS_SPIDEREYES 20
  #define GBUFFERS_HAND 21
  #define GBUFFERS_WEATHER 22

  #define DEFERRED0 23
  #define DEFERRED1 24
  #define DEFERRED2 25
  #define DEFERRED3 26
  #define DEFERRED4 27
  #define DEFERRED5 28
  #define DEFERRED6 29
  #define DEFERRED7 30

  #define GBUFFERS_WATER 31
  #define GBUFFERS_HAND_WATER 32

  #define COMPOSITE0 33
  #define COMPOSITE1 34
  #define COMPOSITE2 35
  #define COMPOSITE3 36
  #define COMPOSITE4 37
  #define COMPOSITE5 38
  #define COMPOSITE6 39
  #define COMPOSITE7 40

  #define FINAL 41

#endif /* INTERNAL_INCLUDED_SYNTAX_SHADERS*/
