/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SYNTAX_OBJECTID
  #define INTERNAL_INCLUDED_SYNTAX_OBJECTID

  cv(int) objectIDMax = 256;
  cRCP(float, objectIDMax);

  #define OBJECT_FALLBACK 255
  
  #define OBJECT_HAND 254
  #define OBJECT_ENTITY 253
  #define OBJECT_PARTICLE 252
  #define OBJECT_WEATHER 251

  #define OBJECT_STAINED_GLASS 250
  #define OBJECT_TRANSPARENT 249
  #define OBJECT_WATER 248
  #define OBJECT_ICE 247
  
  #define OBJECT_EMISSIVE 246
  #define OBJECT_SUBSURFACE 245
  #define OBJECT_TERRAIN 244
  #define OBJECT_METAL 243

#endif /* INTERNAL_INCLUDED_SYNTAX_OBJECTID */
