/*
  JCM2606.
  HALCYON 2.
  PLEASE READ "LICENSE.MD" BEFORE EDITING THIS FILE.
*/

#ifndef INTERNAL_INCLUDED_SYNTAX_SHADERS
  #define INTERNAL_INCLUDED_SYNTAX_SHADERS

  #define FSH 0
  #define VSH 1

  #define SHADOW 1
  
  #define GBUFFERS_BASIC 2
  #define GBUFFERS_BEAM 3
  #define GBUFFERS_CLOUDS 4
  #define GBUFFERS_ENTITIES 5
  #define GBUFFERS_HAND 6
  #define GBUFFERS_SKYBASIC 7
  #define GBUFFERS_SKYTEXTURED 8
  #define GBUFFERS_EYES 9
  #define GBUFFERS_GLINT 10
  #define GBUFFERS_ITEM 11
  #define GBUFFERS_BLOCK 12
  #define GBUFFERS_TERRAIN 13
  #define GBUFFERS_TEXTUREDLIT 14
  #define GBUFFERS_TEXTURED 15
  #define GBUFFERS_WEATHER 16

  #define DEFERRED0 17
  #define DEFERRED1 18
  #define DEFERRED2 19
  #define DEFERRED3 20
  #define DEFERRED4 21
  #define DEFERRED5 22
  #define DEFERRED6 23
  #define DEFERRED7 24

  #define GBUFFERS_WATER 25
  #define GBUFFERS_HANDWATER 26

  #define COMPOSITE0 27
  #define COMPOSITE1 28
  #define COMPOSITE2 29
  #define COMPOSITE3 30
  #define COMPOSITE4 31
  #define COMPOSITE5 32
  #define COMPOSITE6 33
  #define COMPOSITE7 34

  #define FINAL 35

#endif /* INTERNAL_INCLUDED_SYNTAX_SHADERS */
